### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by alexlafroscia**
- Initializes a "normal" Ember addon structure, so that Ember tests could easily be written
- Adds a test to ensure that the library can be imported and used as expected.

### CODE REVIEW

**Comment by alexlafroscia** [comment]
I finally want to tackle #2 but didn't want to do so before first adding some tests to ensure nothing broke, so this seemed like a necessary first step.

**Comment by kpfefferle** [comment]
@alexlafroscia Before diving in on trying to tackle #2, heads up that I just opened #4 to address it.

While I think the test is a good idea, reinitializing the entire default addon structure might be overkill for what's essentially just a shim.

**Comment by alexlafroscia** [comment]
I mean, it doesn't change the user's payload size, and it allows the addon to have tests. Don't see how that's a bad thing...

**Comment by alexlafroscia** [comment]
I was already working on removing Bower, so I PR'd my approach. It was almost the same code as @kpfefferle but removes the vendor shim that isn't actually necessary anymore and keeps the behavior of automatically installing `testdouble` through the blueprint.

**Comment by alexblom** [comment]
Thanks for the working on this @alexlafroscia && @kpfefferle!

**Comment by alexblom** [comment]
Closing so I can deal with #5 in isolation.

**Comment by kpfefferle** [comment]
@alexlafroscia Just to clarify my earlier comment: I fully support the addition of the test. The PR as proposed also would add a bunch of files that go beyond what's necessary to enable the testing - which is specifically the aspect that I might consider overkill for the scope of the PR.

**Comment by alexblom** [comment]
Given we landed @kpfefferle first, re-opened so we can discuss tests in isolation. 

Agreed we don't need all packages. @alexlafroscia do you need help cutting ones the test suite doesn't use? Some easy chops are welcome-page and ajax.

**Comment by alexlafroscia** [comment]
Oh sure, I can reduce that down to the bare minimum needed.

**Comment by alexlafroscia** [comment]
I'm pretty sure everything at this point is kind of the default set of requirements for an Ember addon. I tried removing the dummy app, but you can't. I also don't think that's really necessary... The tests don't get shipped through NPM anyway.

**Comment by alexblom** [comment]
Much appreciated. I typically leave the dummy app as well to support localhost/tests.

**Pull request merged**
